### PR TITLE
seeing if it worked

### PR DESCRIPTION
**Pull request by maxbaldwin**
submitting quiz for review

### CODE REVIEW

**Comment by zoeames** [comment]
this PR isn't done quite right.... did you accidentally do some of your code in master branch?  For now its fine but next time the only thing you should have on master branch is a readme file.  In your quiz branch you should have the rest of the files.

**Comment by maxbaldwin** [comment]
Ah, I had Greg help me earlier before class set this up. He did say that is not how it was normally set up, so that makes sense that it may be off. 

The files should be the same, except that the "quiz" branch should have the comment "something" at the bottom. That was to see if the pull request worked.

**Comment by zoeames** [comment]
ok cool.  its no big deal but it makes it a little harder for me to comment on individual lines.  But everything looks good only 2 minor things to fix before you can merge:
1.  instead of having many different classes (.one, .two, etc) that do the same thing - have 1 class(something like .card)
2.  your text is bumping up to the sides of the articles.  while this isn't a big deal it makes things look a little crowded.  add a little padding so there is a tiny bit of space.

**Comment by maxbaldwin** [comment]
Made the changes, am I supposed to do another "pull"?

**Comment by zoeames** [comment]
no.  it updated this PR with your changes.  you are good to merge :+1:

**Pull request merged**
